import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const WhisperTerms = () => {
  return (
    <div className="min-h-screen bg-background">
      <header className="px-6 md:px-12 lg:px-24 py-6">
        <Link 
          to="/whisper" 
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Whisper
        </Link>
      </header>

      <main className="px-6 md:px-12 lg:px-24 py-12 max-w-3xl">
        <h1 className="text-3xl md:text-4xl font-medium tracking-tight text-foreground mb-8">
          Terms of Service
        </h1>
        
        <div className="prose prose-gray max-w-none space-y-6 text-muted-foreground">
          <p className="text-sm">Last updated: January 2025</p>
          
          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Agreement to Terms</h2>
            <p>
              By accessing or using Whisper ("the App"), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the App.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Description of Service</h2>
            <p>
              Whisper is an AI-powered journaling application that helps users reflect on their thoughts and receive personalized guidance. The App uses artificial intelligence to analyze your entries and provide insights throughout your day.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">User Accounts</h2>
            <p>
              To use certain features of the App, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">User Content</h2>
            <p>
              You retain ownership of all content you create within the App, including journal entries and reflections. By using the App, you grant us a limited license to process your content solely for the purpose of providing and improving our services.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the App for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to the App or its systems</li>
              <li>Interfere with or disrupt the App's functionality</li>
              <li>Reverse engineer or attempt to extract the source code</li>
              <li>Use the App to harass, abuse, or harm others</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Subscription and Payments</h2>
            <p>
              Some features of Whisper require a paid subscription. Subscription fees are billed in advance on a recurring basis. You may cancel your subscription at any time through your App Store account settings.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Intellectual Property</h2>
            <p>
              The App and its original content, features, and functionality are owned by Studio Eight LLC and are protected by international copyright, trademark, and other intellectual property laws.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Disclaimer</h2>
            <p>
              Whisper is provided "as is" without warranties of any kind. The insights and guidance provided by the App are generated by AI and should not be considered professional medical, psychological, or therapeutic advice. If you are experiencing mental health issues, please consult a qualified professional.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Studio Eight LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the App.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Termination</h2>
            <p>
              We may terminate or suspend your account and access to the App immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will provide notice of significant changes by posting the new Terms on this page. Your continued use of the App after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-medium text-foreground">Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:support@whisper.io" className="text-foreground underline">
                support@whisper.io
              </a>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
};

export default WhisperTerms;
